In [1]:
import pandas as pd
import numpy as np

In [3]:
df_district = pd.read_csv('../data/raw/district.csv')
df_district

                        district  latitude  longitude
0   Central and Western District  22.28219  114.14486
1                        Eastern  22.27722  114.22519
2               Islands District  22.26382  113.96038
3          Kowloon City District  22.32866  114.19121
4                     Kwai Tsing  22.35288  114.10004
5                      Kwon Tong  22.31326  114.22581
6                          North  22.49471  114.13812
7                  Sai Kung Area  22.38198  114.27017
8                        Sha Tin  22.38715  114.19534
9                   Sham Shui Po  22.32989  114.16250
10                      Southern  22.25801  114.15308
11               Tai Po District  22.43995  114.16540
12            Tsuen Wan District  22.37908  114.10598
13                      Tuen Mun  22.39161  113.96792
14                      Wan Chai  22.27702  114.17232
15                  Wong Tai Sin  22.34299  114.19302
16                 Yau Tsim Mong  22.32105  114.17261
17            Yuen Long District  22.41667  114.05000

In [12]:
df_pop = pd.read_csv('../data/raw/district_pop.csv')
df_pop = df_pop[['district', 'Total', 'Average household sie', 'Median income']]
df_pop[['Total', 'Average household sie', 'Median income']] =df_pop[['Total', 'Average household sie', 'Median income']].replace({',': ''}, regex=True)
df_pop[['Total', 'Average household sie', 'Median income']] = df_pop[['Total', 'Average household sie', 'Median income']].astype(float)
df_pop

,district,Total,Average household sie,Median income
0,Central and Western District,87700.0,2.6,42000.0
1,Wan Chai,63200.0,2.6,40400.0
2,Eastern,188400.0,2.8,31500.0
3,Southern,86200.0,2.9,33000.0
4,Yau Tsim Mong,123600.0,2.5,27900.0
5,Sham Shui Po,164700.0,2.6,22000.0
6,Kowloon City District,146500.0,2.7,29700.0
7,Wong Tai Sin,147200.0,2.7,23300.0
8,Kwon Tong,247400.0,2.7,22200.0
9,Kwai Tsing,176600.0,2.7,23300.0
10,Tsuen Wan District,114100.0,2.8,31800.0
11,Tuen Mun,187200.0,2.6,25400.0
12,Yuen Long District,234700.0,2.8,27000.0
13,North,111300.0,2.7,23300.0
14,Tai Po District,110500.0,2.8,30000.0
15,Sha Tin,245800.0,2.8,27100.0
16,Sai Kung Area,166900.0,2.9,37200.0
17,Islands District,67400.0,2.7,28800.0

In [14]:
df = pd.merge(df_district, df_pop, on='district')
df

,district,latitude,longitude,Total,Average household sie,Median income
0,Central and Western District,22.28219,114.14486,87700.0,2.6,42000.0
1,Eastern,22.27722,114.22519,188400.0,2.8,31500.0
2,Islands District,22.26382,113.96038,67400.0,2.7,28800.0
3,Kowloon City District,22.32866,114.19121,146500.0,2.7,29700.0
4,Kwai Tsing,22.35288,114.10004,176600.0,2.7,23300.0
5,Kwon Tong,22.31326,114.22581,247400.0,2.7,22200.0
6,North,22.49471,114.13812,111300.0,2.7,23300.0
7,Sai Kung Area,22.38198,114.27017,166900.0,2.9,37200.0
8,Sha Tin,22.38715,114.19534,245800.0,2.8,27100.0
9,Sham Shui Po,22.32989,114.16250,164700.0,2.6,22000.0
10,Southern,22.25801,114.15308,86200.0,2.9,33000.0
11,Tai Po District,22.43995,114.16540,110500.0,2.8,30000.0
12,Tsuen Wan District,22.37908,114.10598,114100.0,2.8,31800.0
13,Tuen Mun,22.39161,113.96792,187200.0,2.6,25400.0
14,Wan Chai,22.27702,114.17232,63200.0,2.6,40400.0
15,Wong Tai Sin,22.34299,114.19302,147200.0,2.7,23300.0
16,Yau Tsim Mong,22.32105,114.17261,123600.0,2.5,27900.0
17,Yuen Long District,22.41667,114.05000,234700.0,2.8,27000.0

In [15]:
df.to_csv("../data/processed/districtAll.csv", index=False)